name: Publish to Github

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        source-url: https://nuget.pkg.github.com/mustafagenc/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Build and Generate NuGet Package
      run: dotnet pack -c Release -o out

    - name: Push to GitHub Registry
      run: |
        dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true
